---
name: test

on:
  push:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '10', '12', '14' ]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Setup
        run: npm install

      - name: Run test
        run: npm test
